name: Manual Cypress Test Run

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: true